In [27]:
## GeoJSON으로 서울 지도 데이터 가져오기

import geopandas as gpd

seoul = gpd.read_file("서울_자치구_경계_2017.geojson")

In [28]:
import folium
def draw_map(merged, month):

    m = folium.Map(
        location=[37.5665,126.9780],
        zoom_start=11
    )

    folium.Choropleth(
        geo_data=merged,
        data=merged,
        columns=["자치구명", month],
        key_on="feature.properties.SIG_KOR_NM",
        fill_color="YlOrRd",
        fill_opacity=0.8,
        line_opacity=0.2,
        legend_name=f"{month} CO₂ 배출량"
    ).add_to(m)

    return m

In [29]:
## 탄소가스 배출량 데이터 가져오기
## 데이터 출처 https://energyinfo.seoul.go.kr/energy/custEnergyUsage?menu-id=Z020700

import pandas as pd
from pathlib import Path
import streamlit as st
from streamlit_folium import st_folium

## streamlit으로 먼저 뼈대 만들기
st.title("서울 탄소 배출 지도")
year = st.selectbox(
    "년도",
    [2020,2021,2022,2023,2024,2025, 2026]
)
energy = st.selectbox(
    "에너지원",
    ["전기","가스","지역난방"]
)
month = st.selectbox(
    "월",
    ["1월","2월","3월","4월",
     "5월","6월","7월","8월",
     "9월","10월","11월","12월","1년 총합"]
)

## 데이터 로드
path = Path("온실가스 데이터")

df = pd.read_csv(path/f"{energy}_{year}.csv", skiprows=1)
df = df.rename(columns={"계": "1년 총합"})

## 데이터 다 float으로 바꾸기
cols_df = df.columns[2:15]

for col in cols_df:
    df[col] = pd.to_numeric(
        df[col].astype(str).str.replace(",", "", regex=False),
        errors="coerce"
    )  

## 지도 데이터와 합치기
merged = seoul.merge(
    df,
    left_on="SIG_KOR_NM",
    right_on="자치구명"
)    

## 지도 만들기(월별, 년별)
m = draw_map(merged, month)
 
st_folium(m, width=900, height=700)

2026-07-21 19:19:47.693 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-21 19:19:47.694 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-21 19:19:48.007
  Warning: to view this Streamlit app on a browser, run it with the following
  command:

    streamlit run C:\Users\USER\AppData\Roaming\Python\Python311\site-packages\ipykernel_launcher.py [ARGUMENTS]
2026-07-21 19:19:48.008 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-21 19:19:48.011 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-21 19:19:48.012 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-21 19:19:48.013 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-21 19:19:48.015 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-21 19:19:48.016 Session state does not function when running a script without `streamlit run`
2026-07-21 19:19:48.017 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-21 19:19:48.017 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-21 19:19:48.018 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-21 19:19:48.019 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-21 19:19:48.020 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-21 19:19:48.022 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-21 19:19:48.024 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-21 19:19:48.025 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-21 19:19:48.026 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-21 19:19:48.027 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-21 19:19:48.030 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-21 19:19:48.030 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-21 19:19:48.032 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-21 19:19:48.033 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-21 19:19:48.033 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-21 19:19:48.600 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-21 19:19:48.601 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-21 19:19:48.601 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-21 19:19:48.601 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-21 19:19:48.602 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

{'last_clicked': None,
 'last_object_clicked': None,
 'last_object_clicked_tooltip': None,
 'last_object_clicked_popup': None,
 'all_drawings': None,
 'last_active_drawing': None,
 'bounds': {'_southWest': {'lat': 37.42829747778836,
   'lng': 126.76448395819257},
  '_northEast': {'lat': 37.70145527921411, 'lng': 127.18379492506567}},
 'zoom': 11,
 'last_circle_radius': None,
 'last_circle_polygon': None,
 'selected_layers': None,
 'selected_tags': None,
 'last_geocoder_result': None}

In [ ]:
## 여기서 데이터 다 float으로 바꾸기

cols = elec_26.columns[2:15]

for col in cols:
    elec_26[col] = pd.to_numeric(
        elec_26[col].astype(str).str.replace(",", "", regex=False),
        errors="coerce"
    )

In [ ]:
elec_26

In [9]:
merged = seoul.merge(
    elec_26,
    left_on="SIG_KOR_NM",
    right_on="자치구명"
)

In [10]:
merged

,SIG_CD,SIG_ENG_NM,SIG_KOR_NM,geometry,번호,자치구명,계,1월,2월,3월,4월,5월,6월,7월,8월,9월,10월,11월,12월
0,11110,Jongno-gu,종로구,"POLYGON ((127.00864 37.58047, 127.00871 37.580...",24,종로구,184778.12,67969.42,64449.95,52358.74,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,11140,Jung-gu,중구,"POLYGON ((127.02314 37.57196, 127.02336 37.571...",25,중구,244500.63,90514.27,83148.87,70837.49,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,11170,Yongsan-gu,용산구,"POLYGON ((126.96918 37.55566, 126.96917 37.554...",22,용산구,169873.97,61233.58,59682.21,48958.19,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,11200,Seongdong-gu,성동구,"POLYGON ((127.04341 37.57234, 127.04524 37.571...",17,성동구,163740.77,59289.74,57826.34,46624.68,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,11215,Gwangjin-gu,광진구,"POLYGON ((127.10166 37.5724, 127.10224 37.5721...",7,광진구,147894.73,53006.92,52099.74,42788.07,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,11230,Dongdaemun-gu,동대문구,"POLYGON ((127.07108 37.60732, 127.07117 37.606...",12,동대문구,151946.7,54439.99,54513.21,42993.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,11260,Jungnang-gu,중랑구,"POLYGON ((127.11131 37.62069, 127.11214 37.620...",26,중랑구,128133.33,45562.13,46161.95,36409.26,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,11290,Seongbuk-gu,성북구,"POLYGON ((127.01059 37.58025, 127.0103 37.5802...",18,성북구,169184.88,60512.84,60112.04,48560.01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,11305,Gangbuk-gu,강북구,"POLYGON ((127.00457 37.68508, 127.00553 37.684...",4,강북구,96636.58,34416.59,35123.14,27096.84,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,11320,Dobong-gu,도봉구,"POLYGON ((127.01509 37.64929, 127.01477 37.649...",11,도봉구,102266.86,36529.39,36569.51,29167.96,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,11350,Nowon-gu,노원구,"POLYGON ((127.11085 37.63841, 127.1109 37.6382...",10,노원구,164625.67,59213.57,58631.66,46780.45,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,11380,Eunpyeong-gu,은평구,"POLYGON ((126.95172 37.65489, 126.95186 37.654...",23,은평구,170853.3,60594.41,60748.99,49509.9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,11410,Seodaemun-gu,서대문구,"POLYGON ((126.95268 37.60274, 126.95267 37.602...",15,서대문구,145840.7,53057.7,50197.78,42585.23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,11440,Mapo-gu,마포구,"POLYGON ((126.88888 37.58464, 126.88987 37.584...",14,마포구,263307.1,95083.36,91468.49,76755.25,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,11470,Yangcheon-gu,양천구,"POLYGON ((126.87405 37.54694, 126.87417 37.546...",20,양천구,186848.06,65167.07,65719.62,55961.37,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,11500,Gangseo-gu,강서구,"POLYGON ((126.80645 37.60224, 126.80724 37.601...",5,강서구,290035.52,104469.07,101421.27,84145.17,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,11530,Guro-gu,구로구,"POLYGON ((126.87948 37.51778, 126.88173 37.516...",8,구로구,183541.83,67398.48,63687.33,52456.02,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,11545,Geumcheon-gu,금천구,"POLYGON ((126.87456 37.48537, 126.87456 37.485...",9,금천구,186961.43,69034.5,62610.04,55316.89,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18,11560,Yeongdeungpo-gu,영등포구,"POLYGON ((126.88046 37.55627, 126.88139 37.555...",21,영등포구,274583.97,99971.55,94176.33,80436.09,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19,11590,Dongjak-gu,동작구,"POLYGON ((126.95471 37.51603, 126.95555 37.515...",13,동작구,136568.92,49114.84,48435.2,39018.88,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20,11620,Gwanak-gu,관악구,"POLYGON ((126.92802 37.49502, 126.92822 37.494...",6,관악구,189773.35,67062.94,68619.21,54091.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
21,11650,Seocho-gu,서초구,"POLYGON ((127.01317 37.52259, 127.01318 37.522...",16,서초구,320113.1,114871.27,115045.87,90195.96,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
22,11680,Gangnam-gu,강남구,"POLYGON ((127.03968 37.53584, 127.0398 37.5358...",2,강남구,557798.73,202903.36,197151.22,157744.15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23,11710,Songpa-gu,송파구,"POLYGON ((127.11311 37.54317, 127.11305 37.542...",19,송파구,335121.08,122849.95,118126.08,94145.05,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24,11740,Gangdong-gu,강동구,"POLYGON ((127.17834 37.57058, 127.17835 37.570...",3,강동구,173825.79,62367.82,61700.06,49757.92,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [18]:
import folium

m = folium.Map(location=[37.5665, 126.9780], zoom_start=11)

folium.Choropleth(
    geo_data=merged,
    data=merged,
    columns=["자치구명", "1월"],          # 구 이름, 표시할 값
    key_on="feature.properties.SIG_KOR_NM",  # GeoJSON의 구 이름 컬럼
    fill_color="YlOrRd",
    fill_opacity=0.8,
    line_opacity=0.2,
    legend_name="CO₂ 배출량"
).add_to(m)

m.save("co2_map_1.html")

In [21]:
print(elec_26.iloc[:, 2:15].dtypes)

계      float64
1월     float64
2월     float64
3월     float64
4월     float64
5월     float64
6월     float64
7월     float64
8월     float64
9월     float64
10월    float64
11월    float64
12월    float64
dtype: object

In [19]:
elec_26

,번호,자치구명,계,1월,2월,3월,4월,5월,6월,7월,8월,9월,10월,11월,12월
0,1,총합,"5,138,755.13","1,856,634.77","1,807,426.09","1,474,694.26",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2,강남구,"557,798.73","202,903.36","197,151.22","157,744.15",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,3,강동구,"173,825.79","62,367.82","61,700.06","49,757.92",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,4,강북구,"96,636.58","34,416.59","35,123.14","27,096.84",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,5,강서구,"290,035.52","104,469.07","101,421.27","84,145.17",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,6,관악구,"189,773.35","67,062.94","68,619.21","54,091.20",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,7,광진구,"147,894.73","53,006.92","52,099.74","42,788.07",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,8,구로구,"183,541.83","67,398.48","63,687.33","52,456.02",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,9,금천구,"186,961.43","69,034.50","62,610.04","55,316.89",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,10,노원구,"164,625.67","59,213.57","58,631.66","46,780.45",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,11,도봉구,"102,266.86","36,529.39","36,569.51","29,167.96",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,12,동대문구,"151,946.70","54,439.99","54,513.21","42,993.50",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,13,동작구,"136,568.92","49,114.84","48,435.20","39,018.88",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,14,마포구,"263,307.10","95,083.36","91,468.49","76,755.25",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,15,서대문구,"145,840.70","53,057.70","50,197.78","42,585.23",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,16,서초구,"320,113.10","114,871.27","115,045.87","90,195.96",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,17,성동구,"163,740.77","59,289.74","57,826.34","46,624.68",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,18,성북구,"169,184.88","60,512.84","60,112.04","48,560.01",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18,19,송파구,"335,121.08","122,849.95","118,126.08","94,145.05",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19,20,양천구,"186,848.06","65,167.07","65,719.62","55,961.37",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20,21,영등포구,"274,583.97","99,971.55","94,176.33","80,436.09",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
21,22,용산구,"169,873.97","61,233.58","59,682.21","48,958.19",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
22,23,은평구,"170,853.30","60,594.41","60,748.99","49,509.90",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23,24,종로구,"184,778.12","67,969.42","64,449.95","52,358.74",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24,25,중구,"244,500.63","90,514.27","83,148.87","70,837.49",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25,26,중랑구,"128,133.33","45,562.13","46,161.95","36,409.26",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [16]:
print(elec_26["2월"].dtype)

object

In [27]:
elec_26["1월"] = (
    elec_26["1월"]
    .str.replace(",", "", regex=False)
    .astype(float)
)